# Generated by Django 4.2.11 on 2024-03-20 17:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NappyChange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_and_time", models.DateTimeField()),
                (
                    "nappy_contents",
                    models.CharField(
                        choices=[
                            ("wet", "Wet"),
                            ("dirty", "Dirty"),
                            ("nothing", "Nothing"),
                        ],
                        max_length=10,
                    ),
                ),
                ("rash", models.BooleanField(default=False)),
                ("notes", models.CharField(max_length=500)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="baby_carer",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date_and_time"],
            },
        ),
    ]
