# Generated by Django 4.2.11 on 2024-04-07 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nappy_changes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nappychange",
            name="nappy_contents",
            field=models.CharField(
                choices=[
                    ("wet", "Wet"),
                    ("dirty", "Dirty"),
                    ("wet-and-dirty", "Wet and Dirty"),
                    ("nothing", "Nothing"),
                ],
                max_length=20,
            ),
        ),
    ]
