# Generated by Django 4.2.11 on 2024-03-23 12:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("nappy_changes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nappychange",
            name="notes",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="nappychange",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_nappies",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
