# Generated by Django 4.2.11 on 2024-03-25 10:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nappy_changes', '0004_alter_nappychange_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_and_time', models.DateTimeField()),
                ('feed_type', models.CharField(choices=[('formula', 'Formula'), ('breast', 'Breast')], max_length=10)),
                ('formula_amount_ml', models.IntegerField()),
                ('breast_feed_time_minutes', models.IntegerField()),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feeds_list', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_and_time'],
            },
        ),
    ]
