# Generated by Django 4.2.11 on 2024-03-25 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nappy_changes", "0005_feed"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Feed",
        ),
    ]
