# Generated by Django 4.2.11 on 2024-03-25 11:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Feed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_and_time", models.DateTimeField()),
                (
                    "feed_type",
                    models.CharField(
                        choices=[("formula", "Formula"), ("breast", "Breast")],
                        max_length=10,
                    ),
                ),
                ("formula_amount_ml", models.IntegerField(blank=True)),
                ("breast_feed_time_minutes", models.IntegerField(blank=True)),
                ("notes", models.CharField(blank=True, max_length=200)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feeds_list",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date_and_time"],
            },
        ),
    ]
