# Generated by Django 4.2.11 on 2024-03-29 11:43

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ("feeds", "0002_alter_feed_breast_feed_time_minutes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="feed",
            name="image",
            field=django_resized.forms.ResizedImageField(
                crop=None,
                default="static/images/baby-tracker-default-image.jpg",
                force_format="WEBP",
                keep_meta=True,
                quality=75,
                scale=None,
                size=[400, None],
                upload_to="feeds/",
            ),
        ),
        migrations.AddField(
            model_name="feed",
            name="image_alt",
            field=models.CharField(
                default="Tracker.Baby default image", max_length=100
            ),
        ),
    ]
